### PR TITLE
Feature fitness check and self-test

### PR DESCRIPTION
**Pull request by FlorianZipser**
This pull request includes a mechanism to test Pepper module's whether they fullfill some quality requirements. One of these requirements is the check whether PepperImporter.isImportable(...) is implemented. Another requirement is the self-test, which enables Pepper to run the module under real circumstances in a test environment (with a provided test corpus). For more information see the documentation.

### CODE REVIEW

**Comment by FlorianZipser** [comment]
To run this Pepper version, Salt 3.3.0-SNAPSHOT is required.

**Comment by FlorianZipser** [comment]
To run this Pepper version, Salt 3.3.0-SNAPSHOT is required.

**Comment by FlorianZipser** [comment]
To run this Pepper version, Salt 3.3.0-SNAPSHOT is required.

**Comment by thomaskrause** [comment]
Does not compile
```
[ERROR] /home/travis/build/korpling/pepper/pepper-framework/src/main/java/org/corpus_tools/pepper/core/SelfTestDesc.java:[90,17] error: method compare in class SaltUtil cannot be applied to given types;

[ERROR] 

    G extends SGraph declared in method <G>compare(G)
```

Also a lot of formatting only changes again. Can you revert the files that are not actually changed?

**Comment by thomaskrause** [comment]
Ah, ok. The compiler errors are from the 3.3.0 SNAPSHOT dependency. I propose release the Salt stuff first and then merge this pull request with a stable release dependency (since develop branch must be always able to release)

**Comment by FlorianZipser** [comment]
Unfortunately I fear I cannot just reset the commits, so my plan is to organize and format the entire project in the develop branch and this branch as well.Then I create a new pull request which hopefully ignores formatting stuff.

**Pull request closed without merging**
